# Generated by Django 5.0.7 on 2024-10-31 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_first_name', models.CharField(max_length=200, verbose_name='نام گیرنده')),
                ('receiver_last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی گیرنده')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل گیرنده')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('post_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='نشانی گیرنده')),
                ('province', models.CharField(max_length=300, verbose_name='استان')),
                ('city', models.CharField(max_length=300, verbose_name='شهر')),
                ('building_number', models.CharField(max_length=300, verbose_name='پلاک')),
                ('building_unit', models.CharField(max_length=300, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'ادرس سفارش',
                'verbose_name_plural': 'ادرس های سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('در حال تحویل', 'در حال تحویل'), ('تحویل داده شده', 'تحویل داده شده'), ('در انتظار پرداخت', 'در انتظار پرداخت')], default='در انتظار پرداخت', max_length=100, verbose_name='وضعیت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت شده')),
                ('paid_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OfferCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='کد تخفیف')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='درصد تخفیف')),
                ('inventory', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت استفاده')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
            ],
        ),
    ]
